<?xml version="1.0"?>
<package format="3">
  <name>als_ros</name>
  <version>0.0.1</version>
  <description>ALS ROS utilities ported to ROS 2 (partial).</description>

  <maintainer email="n.akai.goo@gmail.com">akai</maintainer>

  <license>Apache License 2.0</license>

  <author email="n.akai.goo@gmail.com">Naoki Akai</author>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>

  <export/>
</package>
